#!/usr/bin/python3
import sys

def factorize(number_to_check):
    """Find two smaller numbers that multiply to give a given number"""
    factors = []
    for i in range(2, number_to_check // 2 + 1):
        if number_to_check % i == 0:
            factors.append((i, number_to_check // i))
    
    for p, q in factors:
        print(f"{number_to_check}={p}*{q}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)
    
    try:
        with open(sys.argv[1], 'r') as file:
            for line in file:
                number_to_check = int(line.strip())
                factorize(number_to_check)
    except FileNotFoundError:
        print(f"File '{sys.argv[1]}' not found.")
        sys.exit(1)
    except ValueError:
        print("Invalid number in the file.")
        sys.exit(1)

